### ISSUE TITLE
Whitelist cname for amazonforum.com

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1006]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

d1bd3wxsyuz0t7.cloudfront.net

### Why should the domain(s) be unblocked?

Domain is cname for de.amazonforum.com

![Screenshot_20230504-162748](https://user-images.githubusercontent.com/92758042/236238259-16bd0a5a-efbc-4c5c-9217-bbed12ae76d6.png)

**Comment by hagezi** [comment]
**Reason:** Blocked by Quad9 Secure-DNS, but `amazonforum.com` is not blocked by Q9. Despite all the flags, it seems to be a false positive domain.

![grafik](https://user-images.githubusercontent.com/104343908/236241443-275609a7-f6e7-4e4d-91f2-f83b84f423fa.png)

```
Domain:
 - d1bd3wxsyuz0t7.cloudfront.net OK

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF.LT   NO
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           YES
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        YES

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=d1bd3wxsyuz0t7.cloudfront.net
 - VirusTotal      https://www.virustotal.com/en/domain/d1bd3wxsyuz0t7.cloudfront.net/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/d1bd3wxsyuz0t7.cloudfront.net
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fd1bd3wxsyuz0t7.cloudfront.net
 - FortiGuard      https://www.fortiguard.com/webfilter?q=d1bd3wxsyuz0t7.cloudfront.net&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/d1bd3wxsyuz0t7.cloudfront.net?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=d1bd3wxsyuz0t7.cloudfront.net
 - Norton          https://safeweb.norton.com/report/show?url=d1bd3wxsyuz0t7.cloudfront.net
 - OpenDNS         https://domain.opendns.com/d1bd3wxsyuz0t7.cloudfront.net
 - URLVoid         https://www.urlvoid.com/scan/d1bd3wxsyuz0t7.cloudfront.net/
 - Yandex          https://yandex.com/safety/?l10n=en&url=d1bd3wxsyuz0t7.cloudfront.net
```
