### ISSUE TITLE
epider.me

### ISSUE THREAD

**Issue by 3xploiton3** [hagezi/dns-blocklists#1106]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

epider.me

### Why should the domain(s) be unblocked?

hosting site

**Comment by hagezi** [comment]
Blocked and flagged by Google Safebrowsing.

**Comment by hagezi** [comment]
```
Domain:
 - epider.me       OK

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (2)

 - Threat?
   HaGeZi.TIF.LT   YES
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       258221/-
 - Tranco:         364146/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=epider.me
 - VirusTotal      https://www.virustotal.com/en/domain/epider.me/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/epider.me
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fepider.me
 - FortiGuard      https://www.fortiguard.com/webfilter?q=epider.me&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/epider.me?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=epider.me
 - Norton          https://safeweb.norton.com/report/show?url=epider.me
 - OpenDNS         https://domain.opendns.com/epider.me
 - URLVoid         https://www.urlvoid.com/scan/epider.me/
 - Yandex          https://yandex.com/safety/?l10n=en&url=epider.me
```
