### ISSUE TITLE
link.space

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#1408]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

`link.space`

### Why should the domain(s) be unblocked?

Not a malicious domain and its competitor `linktr.ee` isn't blocked either.

**Comment by hagezi** [comment]
```
Domain:
 - link.space      OK

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (2)

 - Threat?
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           YES
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        YES

 - Phishing?
   Phishing.Army   YES
   PT/OP/PH        NO
   CERT.PL         YES
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       582183/-
 - Tranco:         662962/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      OK
 - OISD            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=link.space
 - VirusTotal      https://www.virustotal.com/en/domain/link.space/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/link.space
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Flink.space
 - FortiGuard      https://www.fortiguard.com/webfilter?q=link.space&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/link.space?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=link.space
 - Norton          https://safeweb.norton.com/report/show?url=link.space
 - OpenDNS         https://domain.opendns.com/link.space
 - URLVoid         https://www.urlvoid.com/scan/link.space/
 - Yandex          https://yandex.com/safety/?l10n=en&url=link.space
```

**Comment by hagezi** [comment]
Too many flags for unblocking, and blocked by the SecureDNS reference Quad9.

**Comment by gyCfjSnO** [comment]
> Too many flags for unblocking, and blocked by the SecureDNS reference Quad9.

@hagezi Can you please check `https://linktr.ee` in your special tool, I'm interested to see if it gets a similar result. It's also a social media landing page however it's not blocked by HaGeZi.

**Comment by hagezi** [comment]
```
Domain:
 - linktr.ee       OK

Malware/Phishing/Scam:
 - Malicous?       NO

 - Threat?
   HaGeZi.TIF      NO
   HaGeZi.TIF.RAW  NO
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       15133/530349
 - Tranco:         406/-
 - Chrome:         585/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=linktr.ee
 - VirusTotal      https://www.virustotal.com/en/domain/linktr.ee/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/linktr.ee
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Flinktr.ee
 - FortiGuard      https://www.fortiguard.com/webfilter?q=linktr.ee&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/linktr.ee?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=linktr.ee
 - Norton          https://safeweb.norton.com/report/show?url=linktr.ee
 - OpenDNS         https://domain.opendns.com/linktr.ee
 - URLVoid         https://www.urlvoid.com/scan/linktr.ee/
 - Yandex          https://yandex.com/safety/?l10n=en&url=linktr.ee
```
