### ISSUE TITLE
bitgrip.com is a false positive

### ISSUE THREAD

**Issue by bitgrip-user** [hagezi/dns-blocklists#1503]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

`bitgrip.com`

### Why should the domain(s) be unblocked?

bitgrip.com is a website of a Berlin based software development company.

Hello, I'm the webmaster at Bitgrip in Berlin. We're a digital agency and purchased the domain [www.bitgrip.com](http://www.bitgrip.com/) a year ago.

We've ended up on a blacklist with the IP address of our website. As a result, the domain is now being blocked by ad blockers, and our website through [bitgrip.com](http://bitgrip.com/) is no longer accessible. The IP of [bitgrip.com](http://bitgrip.com/) has an A-record pointing to an IP that is not hosted with our hosting provider Strato, but rather referencing a CDN hosted by Amazon. Currently, I can't ascertain how this blacklisting occurred. The repository contains too many changes that cannot be definitively traced on GitHub due to the size of the files...

I have two questions: What options do I have as a webmaster to remove the domain from the blacklist? I would also like to understand how this entry came about. Please provide me with feedback on both topics.

thx and have a nice day

**Comment by hagezi** [comment]
@bitgrip-user The IP was apparently flagged by a security service, which is why the domain ended up on my TIF list. However, the domain/IP can no longer be found in any security service. It will be removed from my lists.

**Comment by bitgrip-user** [comment]
thx @hagezi for the quick help and infos here...

**Comment by hagezi** [comment]
@bitgrip-user Actually, it should have been removed automatically when it is no longer flagged. I am trying to find out why this did not happen. Sorry...

**Comment by hagezi** [comment]
```
Domain:
 - bitgrip.com     OK

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     grep: /media/nas/git/dns-data-collection/sources/mitchellkrogza_phishing.database_phishing-domains-active.txt: No such file or directory
YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bitgrip.com
 - VirusTotal      https://www.virustotal.com/en/domain/bitgrip.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bitgrip.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbitgrip.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bitgrip.com&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/bitgrip.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bitgrip.com
 - Norton          https://safeweb.norton.com/report/show?url=bitgrip.com
 - OpenDNS         https://domain.opendns.com/bitgrip.com
 - URLVoid         https://www.urlvoid.com/scan/bitgrip.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bitgrip.com

```
