### ISSUE TITLE
acgnet.cn

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#159]
http://www.acgnet.cn/

website of China Animation Comic Game Group

included in TI list

**Comment by hagezi** [comment]
@sr093906 

Blocked by some SafeDNS, like Cloudflare, AdGuard, ...
According to Google Safebrowsing the page is "clean".

Can't check the page as I can't seem to access it in my region. The call ends in a timeout.

**Comment by hagezi** [comment]
Checked AlienVault & co, I think it is now a false positive domain.

**Comment by hagezi** [comment]
@sr093906 Thanks, removed.

**Comment by sjhgvr** [comment]
https://i.imgur.com/Ogjy3kB.png

**Comment by hagezi** [comment]
Yes, Virustotal ...
Its whitelisted in Quad9, Google Safebrowsing, OpenDNS, Cleanbrowsing, Yandex, Commodo.
I'll keep an eye on that ...

**Comment by sjhgvr** [comment]
https://sitecheck.sucuri.net/results/acgnet.cn
https://www.siteadvisor.com/sitereport.html?url=acgnet.cn
https://safeweb.norton.com/report/show?url=acgnet.cn
https://www.urlvoid.com/scan/acgnet.cn/

**Comment by hagezi** [comment]
Thanks, it's 50:50, so the domain better stay blocked. Some of the "big ones" say it's not a threat, others say dangerous.

**Comment by devipasigner** [comment]
> Thanks, it's 50:50, so the domain better stay blocked. Some of the "big ones" say it's not a threat, others say dangerous.

Must be cautious when checking malicious domains! Haha. It can be hard to tell sometimes.

**Comment by bestplayerbot** [comment]
![Uploading image.png…]()
I don't see a problem with it.

**Comment by hagezi** [comment]
True words Stephan ;)

**Comment by bestplayerbotphone** [comment]
@hagezi it's still there, is it meant to be blocked?

**Comment by hagezi** [comment]
removed and added again, blocked and flagged by too many SecureDNS/Services.

If the operator does not want the domain to end up on blocklists again and again, he should make sure that he gets rid of the flags.

![grafik](https://user-images.githubusercontent.com/104343908/222943537-c35153df-3e09-4604-8aba-f1719ac633c3.png)

```
Domain:
 - acgnet.cn       OK

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF.LT   YES
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=acgnet.cn
 - VirusTotal      https://www.virustotal.com/en/domain/acgnet.cn/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/acgnet.cn
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Facgnet.cn
 - FortiGuard      https://www.fortiguard.com/webfilter?q=acgnet.cn&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/acgnet.cn?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=acgnet.cn
 - Norton          https://safeweb.norton.com/report/show?url=acgnet.cn
 - OpenDNS         https://domain.opendns.com/acgnet.cn
 - URLVoid         https://www.urlvoid.com/scan/acgnet.cn/
 - Yandex          https://yandex.com/safety/?l10n=en&url=acgnet.cn
```
