### ISSUE TITLE
www.urlis.net

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#1702]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

`www.urlis.net`

### Why should the domain(s) be unblocked?

URL Shortener from `https://www.shortlink.net/`

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/3f098a26-d7b1-41b3-b49e-ddade831ae52)


```
Domain:
 - urlis.net       OK

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF.RAW  YES
   DNS0.eu         NO
   Quad9           NO
   Umbrella        NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO
   CERT.PL         NO

 - Phishing?
   Phishing.Army   YES
   PT/OP/PH        NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         369006/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.TIF      BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - NextDNS         OK
 - OISD.Big        BLOCKED
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=urlis.net
 - VirusTotal      https://www.virustotal.com/en/domain/urlis.net/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/urlis.net
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Furlis.net
 - FortiGuard      https://www.fortiguard.com/webfilter?q=urlis.net&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/urlis.net?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=urlis.net
 - Norton          https://safeweb.norton.com/report/show?url=urlis.net
 - OpenDNS         https://domain.opendns.com/urlis.net
 - URLVoid         https://www.urlvoid.com/scan/urlis.net/
 - Yandex          https://yandex.com/safety/?l10n=en&url=urlis.net
```
