### ISSUE TITLE
WDTPRS

### ISSUE THREAD

**Issue by dmbmke** [hagezi/dns-blocklists#1998]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

https://wdtprs.com

### Why should the domain(s) be unblocked?

Just a blog. Uses Amazon referral links but the content is legitimate.

**Comment by hagezi** [comment]
Hi @dmbmke, thanks.

Via https://github.com/scafroglia93/blocklists/blob/5cb70eb3b198cbc51cf013f2ae52deb9896be121/blocklists-malware-traffic.txt#L19

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/46fecc3d-80c9-4840-805a-92273e722ca9)

@scafroglia93

**Comment by hagezi** [comment]
@@scafroglia93 Not flagged, not blocked by any secure dns:

```
Domain:
 - wdtprs.com      OK

Malware/Phishing/Scam:

 - Threat?
   HaGeZi.TIF.RAW  YES
   DNS0.eu         NO
   DNS0.eu ZERO    NO
   Quad9           NO
   Umbrella        NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   CERT.PL         NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO

Top 1M:
 - Umbrella:       NO
 - Cloudflare:     YES
 - Tranco:         YES
 - Majestic:       YES
 - BuiltWith:      NO
 - Chrome:         YES

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - NextDNS         OK
 - OISD.Big        BLOCKED
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=wdtprs.com
 - VirusTotal      https://www.virustotal.com/en/domain/wdtprs.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/wdtprs.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fwdtprs.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=wdtprs.com&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/wdtprs.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=wdtprs.com
 - Norton          https://safeweb.norton.com/report/show?url=wdtprs.com
 - OpenDNS         https://domain.opendns.com/wdtprs.com
 - URLVoid         https://www.urlvoid.com/scan/wdtprs.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=wdtprs.com
```
