### ISSUE TITLE
Spotify Jam not working

### ISSUE THREAD

**Issue by ElliotS2007** [hagezi/dns-blocklists#2024]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

device-api.urbanairship.com

### Why should the domain(s) be unblocked?

The domain is used for Spotify Jam, it is not possible to join a Spotify Jam when this domain is blocked.

**Comment by hagezi** [comment]
@ElliotS2007 not blocked in Pro++, only blocked in Ultimate.

**Comment by ElliotS2007** [comment]
Hmm... this seems to be a problem with NextDNS then...  
<img width="399" alt="image" src="https://github.com/hagezi/dns-blocklists/assets/67877214/80e665e2-74df-427e-b6fc-15f69a254d19">

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/e0ecc2c0-24e5-4aa9-858f-e88f13668989)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/6d30a9d4-f8d9-49be-925c-48fbd4b7369c)

**Comment by hagezi** [comment]
@ElliotS2007 

```
Domain:
 - device-api.urbanairship.com OK

Malware/Phishing/Scam:

 - Threat?
   HaGeZi.TIF.RAW  NO
   DNS0.eu         NO
   DNS0.eu ZERO    NO
   Quad9           NO
   Umbrella        NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   CERT.PL         NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO

Top 1M:
 - Umbrella:       YES
 - Cloudflare:     NO
 - Tranco:         NO
 - Majestic:       NO
 - BuiltWith:      NO
 - Chrome:         NO

Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CFIEC           OK
 - CleanBrowsing   OK
 - Cloudflare      OK
 - ComodoSecure    OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - DNSWatchGO      OK
 - HaGeZi.TIF      OK
 - Neustar         OK
 - NextDNS.TIF_AI  OK
 - NortonCS        OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK
 - YandexSafe      OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    BLOCKED
 - EasyList        BLOCKED
 - GoodbyeAds      BLOCKED
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - NextDNS.AT      BLOCKED
 - OISD.Big        OK
 - OISD.Small      OK
 - QuidsUp.NOTRACK BLOCKED
 - StevenBlack     BLOCKED

```
