### ISSUE TITLE
The unbound folder + lists are redundant

### ISSUE THREAD

**Issue by spirillen** [hagezi/dns-blocklists#3127]
You do acknowledge unbound are support the full stack of RPZ today, this means the old way for blacklisting stuff with unbound is waste of space and a redundancy of the RPZ lists you provide.

```
server:
    module-config: "respip validator iterator"
rpz:
    # The name of the RPZ authority zone
    name: hagezi.anti.piracy

    # The filename where the zone is stored. If left empty
    zonefile: hagezi.anti.piracy

    # The location of the remote RPZ zonefile.
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/anti.piracy.txt

    # Always use this RPZ action for matching triggers from this zone.
    # Possible action are: nxdomain, nodata, passthru, drop, disabled,
    # and cname.
    # rpz-action-override: nxdomain

    # Log all applied RPZ actions for this RPZ zone. Default is no.
    # rpz-log: yes

    # Specify a string to be part of the log line.
    # rpz-log-name: hagezi_anti_piracy
```

https://unbound.docs.nlnetlabs.nl/en/latest/topics/filtering/rpz.html
