### ISSUE TITLE
rsload.net

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#4755]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

rsload.net

### Why should the domain(s) be unblocked?

I get the point. Suspicious software, but it's clean.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @fmhy https://github.com/fmhy/FMHYFilterlist/blob/main/filterlist-basic-abp.txt
Blocked by Cloudflare Secure-DNS

Flagged by CRDF, SOCRadar, Seclookup and alphaMountain.ai

```
Domain:
 - rsload.net      OK

Malware/Phishing/Scam:
 - Threat?
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   USOM            NO
   CERT.PL         NO

 - Scam/Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   Jarelllama SCAM NO

 - NRD?
   NRD 30          NO

Top 1M:
 - Umbrella:       NO
 - Cloudflare:     YES
 - Tranco:         YES
 - Majestic:       YES
 - BuiltWith:      NO
 - Chrome:         YES

Top 10M:
 - DOMCOP:         YES

Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - ComodoSecure    OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - DNSWatchGO      OK
 - HaGeZi.TIF      BLOCKED
 - Neustar         OK
 - NortonCS        OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK
 - YandexSafe      OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - CONTROLD.AT     OK
 - DevDansHosts    OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      BLOCKED
 - HaGeZi.ULTIMATE OK
 - OISD.Big        OK
 - OISD.Small      OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=rsload.net
 - VirusTotal      https://www.virustotal.com/en/domain/rsload.net/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/rsload.net
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Frsload.net
 - FortiGuard      https://www.fortiguard.com/webfilter?q=rsload.net&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/rsload.net?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=rsload.net
 - Norton          https://safeweb.norton.com/report/show?url=rsload.net
 - OpenDNS         https://domain.opendns.com/rsload.net
 - URLVoid         https://www.urlvoid.com/scan/rsload.net/
 - Yandex          https://yandex.com/safety/?l10n=en&url=rsload.net
 - ThreatMiner     https://www.threatminer.org/domain.php?q=rsload.net
```
