### ISSUE TITLE
typeorm.io

### ISSUE THREAD

**Issue by Azuky** [hagezi/dns-blocklists#4763]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

typeorm.io

### Why should the domain(s) be unblocked?

I don't see why typeorm.io should be blocked. It's the documentation of a nodejs (Javascript runtime environment) ORM (Object Relational Mapper). This page is used by many programmers to lookup for the documentation and learn how to use this tool.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
via @mikhailkasimov phishing feed

**Comment by hagezi** [comment]
```
Domain:
 - typeorm.io      OK

Malware/Phishing/Scam:
 - Threat?
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   USOM            NO
   CERT.PL         NO

 - Scam/Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   Jarelllama SCAM NO

 - NRD?
   NRD 30          NO

Top 1M:
 - Umbrella:       NO
 - Cloudflare:     YES
 - Tranco:         YES
 - Majestic:       YES
 - BuiltWith:      NO
 - Chrome:         NO

Top 10M:
 - DOMCOP:         YES

Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CleanBrowsing   OK
 - Cloudflare      OK
 - ComodoSecure    OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - DNSWatchGO      OK
 - HaGeZi.TIF      BLOCKED
 - Neustar         OK
 - NortonCS        OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK
 - YandexSafe      OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - CONTROLD.AT     OK
 - DevDansHosts    OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      BLOCKED
 - HaGeZi.ULTIMATE OK
 - OISD.Big        OK
 - OISD.Small      OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=typeorm.io
 - VirusTotal      https://www.virustotal.com/en/domain/typeorm.io/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/typeorm.io
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Ftypeorm.io
 - FortiGuard      https://www.fortiguard.com/webfilter?q=typeorm.io&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/typeorm.io?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=typeorm.io
 - Norton          https://safeweb.norton.com/report/show?url=typeorm.io
 - OpenDNS         https://domain.opendns.com/typeorm.io
 - URLVoid         https://www.urlvoid.com/scan/typeorm.io/
 - Yandex          https://yandex.com/safety/?l10n=en&url=typeorm.io
 - ThreatMiner     https://www.threatminer.org/domain.php?q=typeorm.io

```
