### ISSUE TITLE
1377x.to

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#493]
#### Which domain(s) should be blocked?
`1377x.to`

#### Why should the domain(s) be blocked?
See https://reddit.com/r/Piracy/comments/117fq8t/just_a_quick_heads_up_for_anyone_who_uses_1337xto/

**Comment by devipasigner** [comment]
Awesome find :smile:

**Comment by hagezi** [comment]
Thanks, will block ...

```
Domain:
 - 1377x.to

Malware/Phishing/Scam:
 - Malicous?       NO

Top 1M rank:
 - Umbrella:       300627/311253
 - Tranco:         2623/-
 - Chrome:         -/429

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=1377x.to
 - VirusTotal      https://www.virustotal.com/en/domain/1377x.to/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/1377x.to
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2F1377x.to
 - FortiGuard      https://www.fortiguard.com/webfilter?q=1377x.to
 - Kaspersky       https://opentip.kaspersky.com/1377x.to?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=1377x.to
 - Norton          https://safeweb.norton.com/report/show?url=1377x.to
 - OpenDNS         https://domain.opendns.com/1377x.to
 - URLVoid         https://www.urlvoid.com/scan/1377x.to/
 - Yandex          https://yandex.com/safety/?l10n=en&url=1377x.to
```
