### ISSUE TITLE
arogapopin.ac.id

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#502]
Indonesian academic body

flagged by one vendor on VT

https://www.virustotal.com/gui/url/209d16d3701be5600e46d8b7a0535e940e18aa6d729886fc6984f50ef6a42674/detection
https://rethinkdns.com/search?q=arogapopin.ac.id

**Comment by hagezi** [comment]
Blocked by Quad9

```
Domain:
 - arogapopin.ac.id

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         872040/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=arogapopin.ac.id
 - VirusTotal      https://www.virustotal.com/en/domain/arogapopin.ac.id/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/arogapopin.ac.id
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Farogapopin.ac.id
 - FortiGuard      https://www.fortiguard.com/webfilter?q=arogapopin.ac.id
 - Kaspersky       https://opentip.kaspersky.com/arogapopin.ac.id?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=arogapopin.ac.id
 - Norton          https://safeweb.norton.com/report/show?url=arogapopin.ac.id
 - OpenDNS         https://domain.opendns.com/arogapopin.ac.id
 - URLVoid         https://www.urlvoid.com/scan/arogapopin.ac.id/
 - Yandex          https://yandex.com/safety/?l10n=en&url=arogapopin.ac.id
```
