### ISSUE TITLE
burmancoffee.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#503]
https://www.virustotal.com/gui/url/5533519f38912bc353d6cd3d8914145f26d0661881ea794e609ad24565da5a69/detection
https://rethinkdns.com/search?q=burmancoffee.com

Included in https://threatview.io/Downloads/DOMAIN-High-Confidence-Feed.txt

suspect the feed integrates data from CRDF

**Comment by hagezi** [comment]
Can't check ...

![grafik](https://user-images.githubusercontent.com/104343908/220883484-184da522-c68d-4062-adff-eeeec164d773.png)
```

Domain:
 - burmancoffee.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         938915/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=burmancoffee.com
 - VirusTotal      https://www.virustotal.com/en/domain/burmancoffee.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/burmancoffee.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fburmancoffee.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=burmancoffee.com
 - Kaspersky       https://opentip.kaspersky.com/burmancoffee.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=burmancoffee.com
 - Norton          https://safeweb.norton.com/report/show?url=burmancoffee.com
 - OpenDNS         https://domain.opendns.com/burmancoffee.com
 - URLVoid         https://www.urlvoid.com/scan/burmancoffee.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=burmancoffee.com
```

**Comment by bestplayerbot** [comment]
Doesn't show anything for me

**Comment by hagezi** [comment]
Blocked by ThreatView.

```
Domain:
 - burmancoffee.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      YES
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         938915/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=burmancoffee.com
 - VirusTotal      https://www.virustotal.com/en/domain/burmancoffee.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/burmancoffee.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fburmancoffee.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=burmancoffee.com
 - Kaspersky       https://opentip.kaspersky.com/burmancoffee.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=burmancoffee.com
 - Norton          https://safeweb.norton.com/report/show?url=burmancoffee.com
 - OpenDNS         https://domain.opendns.com/burmancoffee.com
 - URLVoid         https://www.urlvoid.com/scan/burmancoffee.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=burmancoffee.com

```
