### ISSUE TITLE
03e.info

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#504]
a porn site?

http://03e.info/russkoe/809-video_lyubitel_skoe_staroe_porno_pochti_dvadtsatiletney_davnosti_s.html

https://www.virustotal.com/gui/url/7234b8fb03b70f4e716298b4ea7458540eca2763d587b8c95e15d1a44cc35701?nocache=1
https://rethinkdns.com/search?q=03e.info

**Comment by hagezi** [comment]
Blocked by Matomo Referrer Spam, Badd Boyz Hosts, SecureDNS
```
Domain:
 - 03e.info

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         507769/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=03e.info
 - VirusTotal      https://www.virustotal.com/en/domain/03e.info/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/03e.info
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2F03e.info
 - FortiGuard      https://www.fortiguard.com/webfilter?q=03e.info
 - Kaspersky       https://opentip.kaspersky.com/03e.info?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=03e.info
 - Norton          https://safeweb.norton.com/report/show?url=03e.info
 - OpenDNS         https://domain.opendns.com/03e.info
 - URLVoid         https://www.urlvoid.com/scan/03e.info/
 - Yandex          https://yandex.com/safety/?l10n=en&url=03e.info
```
