### ISSUE TITLE
aashiyana.tatasteel.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#506]
https://aashiyana.tatasteel.com/in/en.html

https://www.virustotal.com/gui/url/e8629cb5845da7d1455971234f364b9c8de73ce2036c247eb85258f2039bee97/detection
https://rethinkdns.com/search?q=aashiyana.tatasteel.com

**Comment by hagezi** [comment]
Blocked by https://threatfox.abuse.ch/ https://github.com/stamparm/maltrail and some SecureDNS.
```
Domain:
 - aashiyana.tatasteel.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         137144/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=aashiyana.tatasteel.com
 - VirusTotal      https://www.virustotal.com/en/domain/aashiyana.tatasteel.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/aashiyana.tatasteel.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Faashiyana.tatasteel.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=aashiyana.tatasteel.com
 - Kaspersky       https://opentip.kaspersky.com/aashiyana.tatasteel.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=aashiyana.tatasteel.com
 - Norton          https://safeweb.norton.com/report/show?url=aashiyana.tatasteel.com
 - OpenDNS         https://domain.opendns.com/aashiyana.tatasteel.com
 - URLVoid         https://www.urlvoid.com/scan/aashiyana.tatasteel.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=aashiyana.tatasteel.com
```
