### ISSUE TITLE
agrimac.gr

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#508]
Georgian shopping site

https://agrimac.gr/

https://www.virustotal.com/gui/url/f60b845d74acfbdf68aba9c66f077d1e2a94253271871bf04bba41c62c61ab68/details
https://rethinkdns.com/search?q=agrimac.gr

**Comment by hagezi** [comment]
Blocked by https://threatfox.abuse.ch/ and https://urlhaus.abuse.ch/

```
Domain:
 - agrimac.gr

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         267389/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=agrimac.gr
 - VirusTotal      https://www.virustotal.com/en/domain/agrimac.gr/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/agrimac.gr
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fagrimac.gr
 - FortiGuard      https://www.fortiguard.com/webfilter?q=agrimac.gr
 - Kaspersky       https://opentip.kaspersky.com/agrimac.gr?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=agrimac.gr
 - Norton          https://safeweb.norton.com/report/show?url=agrimac.gr
 - OpenDNS         https://domain.opendns.com/agrimac.gr
 - URLVoid         https://www.urlvoid.com/scan/agrimac.gr/
 - Yandex          https://yandex.com/safety/?l10n=en&url=agrimac.gr
```
