### ISSUE TITLE
aksu.edu.ng

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#509]
Akwa Ibom State University – AKSU

https://aksu.edu.ng/newsite/

https://rethinkdns.com/search?q=aksu.edu.ng
https://www.virustotal.com/gui/url/3d2357c98a7d658ba383bccfcb8952bd0741aee29d4b8698bde722842db05b37/detection

**Comment by hagezi** [comment]
Blocked by [phishing.army](https://phishing.army/) and https://gitlab.com/malware-filter/phishing-filter (curated from [PhishTank](https://www.phishtank.com/), [OpenPhish](https://openphish.com/), [phishunt.io](https://phishunt.io/))

ping @drego85: false positve?

```
Domain:
 - aksu.edu.ng

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         693562/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=aksu.edu.ng
 - VirusTotal      https://www.virustotal.com/en/domain/aksu.edu.ng/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/aksu.edu.ng
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Faksu.edu.ng
 - FortiGuard      https://www.fortiguard.com/webfilter?q=aksu.edu.ng
 - Kaspersky       https://opentip.kaspersky.com/aksu.edu.ng?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=aksu.edu.ng
 - Norton          https://safeweb.norton.com/report/show?url=aksu.edu.ng
 - OpenDNS         https://domain.opendns.com/aksu.edu.ng
 - URLVoid         https://www.urlvoid.com/scan/aksu.edu.ng/
 - Yandex          https://yandex.com/safety/?l10n=en&url=aksu.edu.ng

```
