### ISSUE TITLE
aldogallery.ir

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#511]
Persian-language women shopping 

https://rethinkdns.com/search?q=aldogallery.ir
https://www.virustotal.com/gui/url/26ec852f3e84f3fcce28d4318dbf9f1a41ac9acda53327afa7d5fb53ce71b645/detection

**Comment by hagezi** [comment]
[Blocked by ThreatFox](https://threatfox.abuse.ch/), NextDNS AI

```
Domain:
 - aldogallery.ir

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         75492/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=aldogallery.ir
 - VirusTotal      https://www.virustotal.com/en/domain/aldogallery.ir/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/aldogallery.ir
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Faldogallery.ir
 - FortiGuard      https://www.fortiguard.com/webfilter?q=aldogallery.ir
 - Kaspersky       https://opentip.kaspersky.com/aldogallery.ir?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=aldogallery.ir
 - Norton          https://safeweb.norton.com/report/show?url=aldogallery.ir
 - OpenDNS         https://domain.opendns.com/aldogallery.ir
 - URLVoid         https://www.urlvoid.com/scan/aldogallery.ir/
 - Yandex          https://yandex.com/safety/?l10n=en&url=aldogallery.ir
```
