### ISSUE TITLE
alfabit.org

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#512]
https://alfabit.org/ru/about

https://rethinkdns.com/search?q=alfabit.org
https://www.virustotal.com/gui/url/8a5c3925d3023da7ec860660b0ccee3fe7b2eb3c6ba4666da53e1f8d0d96c5f0?nocache=1

**Comment by hagezi** [comment]
Blocked because of phishing activities by phishing.army.

ping @drego85: false positve?

```
Domain:
 - alfabit.org

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         510472/-

Nofilter DNS:
 - Google          OK

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=alfabit.org
 - VirusTotal      https://www.virustotal.com/en/domain/alfabit.org/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/alfabit.org
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Falfabit.org
 - FortiGuard      https://www.fortiguard.com/webfilter?q=alfabit.org
 - Kaspersky       https://opentip.kaspersky.com/alfabit.org?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=alfabit.org
 - Norton          https://safeweb.norton.com/report/show?url=alfabit.org
 - OpenDNS         https://domain.opendns.com/alfabit.org
 - URLVoid         https://www.urlvoid.com/scan/alfabit.org/
 - Yandex          https://yandex.com/safety/?l10n=en&url=alfabit.org

```
