### ISSUE TITLE
alimco.in

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#514]
Home Page: Artificial Limbs Manufacturing Corporation of India

https://www.alimco.in/

https://www.virustotal.com/gui/url/c857143a6509dd855a9fff003f59b9418417e2b012f2006318fa7204b952c06c?nocache=1
https://rethinkdns.com/search?q=alimco.in

**Comment by hagezi** [comment]
Will be removed, false positive, ping malware source @th3m3

```
Domain:
 - alimco.in

Malware/Phishing/Scam:
 - Malicous?       LIKELY (3)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         946853/441233

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=alimco.in
 - VirusTotal      https://www.virustotal.com/en/domain/alimco.in/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/alimco.in
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Falimco.in
 - FortiGuard      https://www.fortiguard.com/webfilter?q=alimco.in
 - Kaspersky       https://opentip.kaspersky.com/alimco.in?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=alimco.in
 - Norton          https://safeweb.norton.com/report/show?url=alimco.in
 - OpenDNS         https://domain.opendns.com/alimco.in
 - URLVoid         https://www.urlvoid.com/scan/alimco.in/
 - Yandex          https://yandex.com/safety/?l10n=en&url=alimco.in
```
