### ISSUE TITLE
almaweb.uni-leipzig.de

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#515]
Welcome to the AlmaWeb study portal

https://www.virustotal.com/gui/url/d8b4e22df3eaafecb0ca278b6a43300c3cde19c503fff48f5e6aefe9ec6ba421
https://rethinkdns.com/search?q=almaweb.uni-leipzig.de

**Comment by hagezi** [comment]
Blocked because Phishing 

ping @mitchellkrogza: False positve?

```
Domain:
 - almaweb.uni-leipzig.de

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         469871/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=almaweb.uni-leipzig.de
 - VirusTotal      https://www.virustotal.com/en/domain/almaweb.uni-leipzig.de/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/almaweb.uni-leipzig.de
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Falmaweb.uni-leipzig.de
 - FortiGuard      https://www.fortiguard.com/webfilter?q=almaweb.uni-leipzig.de
 - Kaspersky       https://opentip.kaspersky.com/almaweb.uni-leipzig.de?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=almaweb.uni-leipzig.de
 - Norton          https://safeweb.norton.com/report/show?url=almaweb.uni-leipzig.de
 - OpenDNS         https://domain.opendns.com/almaweb.uni-leipzig.de
 - URLVoid         https://www.urlvoid.com/scan/almaweb.uni-leipzig.de/
 - Yandex          https://yandex.com/safety/?l10n=en&url=almaweb.uni-leipzig.de

```
