### ISSUE TITLE
alqayyumjewellery.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#516]
https://www.virustotal.com/gui/url/b28374413d228e56f39529afca75210072f9a80d3f711feeaa2ddac37b303849?nocache=1
https://rethinkdns.com/search?q=alqayyumjewellery.com

**Comment by hagezi** [comment]
Blocked because Phishing, blocked by some SecureDNS

ping @mitchellkrogza: False positve?

```
Domain:
 - alqayyumjewellery.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         496927/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        BLOCKED
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=alqayyumjewellery.com
 - VirusTotal      https://www.virustotal.com/en/domain/alqayyumjewellery.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/alqayyumjewellery.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Falqayyumjewellery.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=alqayyumjewellery.com
 - Kaspersky       https://opentip.kaspersky.com/alqayyumjewellery.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=alqayyumjewellery.com
 - Norton          https://safeweb.norton.com/report/show?url=alqayyumjewellery.com
 - OpenDNS         https://domain.opendns.com/alqayyumjewellery.com
 - URLVoid         https://www.urlvoid.com/scan/alqayyumjewellery.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=alqayyumjewellery.com

```
