### ISSUE TITLE
analar.az

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#517]
https://www.virustotal.com/gui/url/0096c0644cedff4c599447eaa164c466231ccb13779f3cfb6463ce4fc6f88655?nocache=1
https://rethinkdns.com/search?q=analar.az

A blog site created for moms and women to get every information easily, directly from the experts. It has been operating since 2022.

**Comment by hagezi** [comment]
Phishing, false positive? @mitchellkrogza

```
Domain:
 - analar.az

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         983107/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=analar.az
 - VirusTotal      https://www.virustotal.com/en/domain/analar.az/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/analar.az
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fanalar.az
 - FortiGuard      https://www.fortiguard.com/webfilter?q=analar.az
 - Kaspersky       https://opentip.kaspersky.com/analar.az?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=analar.az
 - Norton          https://safeweb.norton.com/report/show?url=analar.az
 - OpenDNS         https://domain.opendns.com/analar.az
 - URLVoid         https://www.urlvoid.com/scan/analar.az/
 - Yandex          https://yandex.com/safety/?l10n=en&url=analar.az
```
