### ISSUE TITLE
aplaystore.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#518]
https://aplaystore.com/%d8%a3%d9%82%d9%88%d9%89-5-%d8%aa%d8%b7%d8%a8%d9%8a%d9%82%d8%a7%d8%aa-%d8%aa%d9%85-%d8%a8%d8%b1%d9%85%d8%ac%d8%aa%d9%87%d8%a7-%d9%81%d9%8a-%d8%b3%d9%86%d8%a9-2023-%d8%a7%d9%84%d8%b9%d8%af%d9%8a%d8%af/

Arabic IT news site ?

https://rethinkdns.com/search?q=aplaystore.com
https://www.virustotal.com/gui/url/b171f8487cca945e684342d86a8087971073e924fd6fee7891ca85c07672c07e?nocache=1

**Comment by hagezi** [comment]
Blocked by ThreatFox, NextDNS AI

```
Domain:
 - aplaystore.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       YES
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         464368/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=aplaystore.com
 - VirusTotal      https://www.virustotal.com/en/domain/aplaystore.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/aplaystore.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Faplaystore.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=aplaystore.com
 - Kaspersky       https://opentip.kaspersky.com/aplaystore.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=aplaystore.com
 - Norton          https://safeweb.norton.com/report/show?url=aplaystore.com
 - OpenDNS         https://domain.opendns.com/aplaystore.com
 - URLVoid         https://www.urlvoid.com/scan/aplaystore.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=aplaystore.com
```
