### ISSUE TITLE
asimov.academy

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#520]
Programming courses in Python, Data Science & Machine Learning, Dashboards and Quantitative Trading.

https://asimov.academy/

https://rethinkdns.com/search?q=asimov.academy
https://www.virustotal.com/gui/url/40be143c48a168a902ff8727b5458258324a6902e459976ce33e1175c98d718b?nocache=1

**Comment by hagezi** [comment]
Phishing, false positive? @drego85

```
Domain:
 - asimov.academy

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   YES
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         956198/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=asimov.academy
 - VirusTotal      https://www.virustotal.com/en/domain/asimov.academy/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/asimov.academy
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fasimov.academy
 - FortiGuard      https://www.fortiguard.com/webfilter?q=asimov.academy
 - Kaspersky       https://opentip.kaspersky.com/asimov.academy?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=asimov.academy
 - Norton          https://safeweb.norton.com/report/show?url=asimov.academy
 - OpenDNS         https://domain.opendns.com/asimov.academy
 - URLVoid         https://www.urlvoid.com/scan/asimov.academy/
 - Yandex          https://yandex.com/safety/?l10n=en&url=asimov.academy

```
