### ISSUE TITLE
asmecolpoz.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#522]
https://www.virustotal.com/gui/url/44063fbbb512f79d534c4b529d9f4292502e4628fbe976a2e881c776190a9ce0?nocache=1
https://rethinkdns.com/search?q=asmecolpoz.com

 Alternative Medicine

**Comment by hagezi** [comment]
Phishing? False positve @mitchellkrogza?

```
Domain:
 - asmecolpoz.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         190317/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=asmecolpoz.com
 - VirusTotal      https://www.virustotal.com/en/domain/asmecolpoz.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/asmecolpoz.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fasmecolpoz.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=asmecolpoz.com
 - Kaspersky       https://opentip.kaspersky.com/asmecolpoz.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=asmecolpoz.com
 - Norton          https://safeweb.norton.com/report/show?url=asmecolpoz.com
 - OpenDNS         https://domain.opendns.com/asmecolpoz.com
 - URLVoid         https://www.urlvoid.com/scan/asmecolpoz.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=asmecolpoz.com

```
