### ISSUE TITLE
autodeals.pk

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#523]
https://www.virustotal.com/gui/url/d7245ca3d639758f57f109fc72d32e977d98c0db3fc40401863d9bf375a27a7a?nocache=1
https://rethinkdns.com/search?q=autodeals.pk

Pakistan's No #1 automobile website

**Comment by hagezi** [comment]
Phishing, false positive @mitchellkrogz ?
```
Domain:
 - autodeals.pk

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         938982/-
 - Chrome:         881477/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        BLOCKED
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=autodeals.pk
 - VirusTotal      https://www.virustotal.com/en/domain/autodeals.pk/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/autodeals.pk
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fautodeals.pk
 - FortiGuard      https://www.fortiguard.com/webfilter?q=autodeals.pk
 - Kaspersky       https://opentip.kaspersky.com/autodeals.pk?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=autodeals.pk
 - Norton          https://safeweb.norton.com/report/show?url=autodeals.pk
 - OpenDNS         https://domain.opendns.com/autodeals.pk
 - URLVoid         https://www.urlvoid.com/scan/autodeals.pk/
 - Yandex          https://yandex.com/safety/?l10n=en&url=autodeals.pk
```
