### ISSUE TITLE
aveli.link

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#524]
Your all-in-one social tool - Aveli BioLink

https://www.virustotal.com/gui/url/14e0c101c79f8fb2c54c4763198933a4fba6bd85b7b1eef0988ec3dc19560848/detection

**Comment by hagezi** [comment]
And again Phishing, blocked by SecureDNS. 

What are these pages that you post here? Not on the Umbrella and not on the Tranco Toplist. Why do you think?

```
Domain:
 - aveli.link

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   YES
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         450561/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=aveli.link
 - VirusTotal      https://www.virustotal.com/en/domain/aveli.link/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/aveli.link
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Faveli.link
 - FortiGuard      https://www.fortiguard.com/webfilter?q=aveli.link
 - Kaspersky       https://opentip.kaspersky.com/aveli.link?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=aveli.link
 - Norton          https://safeweb.norton.com/report/show?url=aveli.link
 - OpenDNS         https://domain.opendns.com/aveli.link
 - URLVoid         https://www.urlvoid.com/scan/aveli.link/
 - Yandex          https://yandex.com/safety/?l10n=en&url=aveli.link

```
