### ISSUE TITLE
badshop.pl

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#525]
Another polish scam site?

https://rethinkdns.com/search?q=badshop.pl
https://www.virustotal.com/gui/url/1974f2ad1355fe68646f7478fe4199478ded8016d1cc086e364f42bdd0a40160?nocache=1

**Comment by hagezi** [comment]
https://github.com/FiltersHeroes/KADhosts

```
Domain:
 - badshop.pl

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         850578/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=badshop.pl
 - VirusTotal      https://www.virustotal.com/en/domain/badshop.pl/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/badshop.pl
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbadshop.pl
 - FortiGuard      https://www.fortiguard.com/webfilter?q=badshop.pl
 - Kaspersky       https://opentip.kaspersky.com/badshop.pl?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=badshop.pl
 - Norton          https://safeweb.norton.com/report/show?url=badshop.pl
 - OpenDNS         https://domain.opendns.com/badshop.pl
 - URLVoid         https://www.urlvoid.com/scan/badshop.pl/
 - Yandex          https://yandex.com/safety/?l10n=en&url=badshop.pl

```
