### ISSUE TITLE
baraderoteinforma.com.ar

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#526]
news site

https://www.virustotal.com/gui/url/e9158cdfb5ac78943998c29a0780825517fc4a382d16e7e0ba2dca2d42031333?nocache=1
https://rethinkdns.com/search?q=baraderoteinforma.com.ar

**Comment by hagezi** [comment]
On hacked websites malware list.

```
Domain:
 - baraderoteinforma.com.ar

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         841096/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=baraderoteinforma.com.ar
 - VirusTotal      https://www.virustotal.com/en/domain/baraderoteinforma.com.ar/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/baraderoteinforma.com.ar
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbaraderoteinforma.com.ar
 - FortiGuard      https://www.fortiguard.com/webfilter?q=baraderoteinforma.com.ar
 - Kaspersky       https://opentip.kaspersky.com/baraderoteinforma.com.ar?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=baraderoteinforma.com.ar
 - Norton          https://safeweb.norton.com/report/show?url=baraderoteinforma.com.ar
 - OpenDNS         https://domain.opendns.com/baraderoteinforma.com.ar
 - URLVoid         https://www.urlvoid.com/scan/baraderoteinforma.com.ar/
 - Yandex          https://yandex.com/safety/?l10n=en&url=baraderoteinforma.com.ar
```
