### ISSUE TITLE
basecamp-shop.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#527]
https://www.virustotal.com/gui/url/144d6928de42fc32697399b8464428aba5fd86220555ea67d91ac1d38f81abc4?nocache=1
https://rethinkdns.com/search?q=basecamp-shop.com
https://www.scamvoid.net/check/basecamp-shop.com/

**Comment by hagezi** [comment]
```
Domain:
 - basecamp-shop.com

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        YES

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         311416/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=basecamp-shop.com
 - VirusTotal      https://www.virustotal.com/en/domain/basecamp-shop.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/basecamp-shop.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbasecamp-shop.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=basecamp-shop.com
 - Kaspersky       https://opentip.kaspersky.com/basecamp-shop.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=basecamp-shop.com
 - Norton          https://safeweb.norton.com/report/show?url=basecamp-shop.com
 - OpenDNS         https://domain.opendns.com/basecamp-shop.com
 - URLVoid         https://www.urlvoid.com/scan/basecamp-shop.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=basecamp-shop.com

```
