### ISSUE TITLE
baydari.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#530]
Pakistan job seeking site

https://rethinkdns.com/search?q=baydari.com
https://www.virustotal.com/gui/url/4cf4e27b1928f8de6ceab3cac618e06f6b3d40dded97c403cea0fb6269e0c302?nocache=1

**Comment by hagezi** [comment]
```
Domain:
 - baydari.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       YES
   URLhaus         YES
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         506842/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=baydari.com
 - VirusTotal      https://www.virustotal.com/en/domain/baydari.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/baydari.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbaydari.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=baydari.com
 - Kaspersky       https://opentip.kaspersky.com/baydari.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=baydari.com
 - Norton          https://safeweb.norton.com/report/show?url=baydari.com
 - OpenDNS         https://domain.opendns.com/baydari.com
 - URLVoid         https://www.urlvoid.com/scan/baydari.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=baydari.com

```
