### ISSUE TITLE
bbhonline.in

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#531]
hospital

https://www.virustotal.com/gui/url/2ba3d14578cc1cbd9f823fb09afafd41e8546183dea3884cb509e8f6ad873cc0/detection
https://rethinkdns.com/search?q=bbhonline.in

**Comment by hagezi** [comment]
False positive, ping malware source @th3m3

```
Domain:
 - bbhonline.in

Malware/Phishing/Scam:
 - Malicous?       LIKELY (4)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         831731/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bbhonline.in
 - VirusTotal      https://www.virustotal.com/en/domain/bbhonline.in/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bbhonline.in
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbbhonline.in
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bbhonline.in
 - Kaspersky       https://opentip.kaspersky.com/bbhonline.in?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bbhonline.in
 - Norton          https://safeweb.norton.com/report/show?url=bbhonline.in
 - OpenDNS         https://domain.opendns.com/bbhonline.in
 - URLVoid         https://www.urlvoid.com/scan/bbhonline.in/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bbhonline.in
```
