### ISSUE TITLE
bbva.viajes.despegar.com.co

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#532]
https://bbva.viajes.despegar.com.co/login-redirect

https://www.virustotal.com/gui/url/1cab5f712d9497df9268ac7ef1c1cf9d3d184385744d92b4af17d453416f934e?nocache=1
https://rethinkdns.com/search?q=bbva.viajes.despegar.com.co

It is labelled as a phishing site.

However, clicking the 'Ingresar' button redirect you to...

https://www.bbva.com.co/personas/acceso.html

**Comment by hagezi** [comment]
Phishing, report here: https://gitlab.com/malware-filter/phishing-filter

```
Domain:
 - bbva.viajes.despegar.com.co

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        YES
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         560706/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bbva.viajes.despegar.com.co
 - VirusTotal      https://www.virustotal.com/en/domain/bbva.viajes.despegar.com.co/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bbva.viajes.despegar.com.co
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbbva.viajes.despegar.com.co
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bbva.viajes.despegar.com.co
 - Kaspersky       https://opentip.kaspersky.com/bbva.viajes.despegar.com.co?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bbva.viajes.despegar.com.co
 - Norton          https://safeweb.norton.com/report/show?url=bbva.viajes.despegar.com.co
 - OpenDNS         https://domain.opendns.com/bbva.viajes.despegar.com.co
 - URLVoid         https://www.urlvoid.com/scan/bbva.viajes.despegar.com.co/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bbva.viajes.despegar.com.co

```
