### ISSUE TITLE
beffino.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#533]
https://www.virustotal.com/gui/url/0c56e8185ad4ce5bcddda4574c193b3da17fb45fd7b95ceaf88f10a6f5e99d29?nocache=1
https://rethinkdns.com/search?q=beffino.com

not sure whether it is a scam site

**Comment by hagezi** [comment]
```
Domain:
 - beffino.com

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        YES

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         228196/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=beffino.com
 - VirusTotal      https://www.virustotal.com/en/domain/beffino.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/beffino.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbeffino.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=beffino.com
 - Kaspersky       https://opentip.kaspersky.com/beffino.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=beffino.com
 - Norton          https://safeweb.norton.com/report/show?url=beffino.com
 - OpenDNS         https://domain.opendns.com/beffino.com
 - URLVoid         https://www.urlvoid.com/scan/beffino.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=beffino.com

```
