### ISSUE TITLE
bestengineeringprojects.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#534]
https://rethinkdns.com/search?q=bestengineeringprojects.com
https://www.virustotal.com/gui/url/514fe34b419f268576e4029aa470e93634eda57f6c819699bb10a2633e62fbad?nocache=1

including 'best' in domain doesn't means the site must be a phishing site.

**Comment by hagezi** [comment]
Phishing, report here: https://github.com/mitchellkrogza/Phishing.Database

```
Domain:
 - bestengineeringprojects.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         921320/-
 - Chrome:         889556/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         BLOCKED
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bestengineeringprojects.com
 - VirusTotal      https://www.virustotal.com/en/domain/bestengineeringprojects.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bestengineeringprojects.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbestengineeringprojects.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bestengineeringprojects.com
 - Kaspersky       https://opentip.kaspersky.com/bestengineeringprojects.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bestengineeringprojects.com
 - Norton          https://safeweb.norton.com/report/show?url=bestengineeringprojects.com
 - OpenDNS         https://domain.opendns.com/bestengineeringprojects.com
 - URLVoid         https://www.urlvoid.com/scan/bestengineeringprojects.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bestengineeringprojects.com

```
