### ISSUE TITLE
bestnfast.pl

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#535]
https://rethinkdns.com/search?q=bestnfast.pl
https://www.virustotal.com/gui/url/2247a255731f53e9a442e9288d9f5685856bfee49ece5c76033bc2f66d4aa56e?nocache=1

Polish scam?

**Comment by hagezi** [comment]
```
Domain:
 - bestnfast.pl

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        YES

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         404353/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - OVPN            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
 - Tiarap          BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bestnfast.pl
 - VirusTotal      https://www.virustotal.com/en/domain/bestnfast.pl/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bestnfast.pl
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbestnfast.pl
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bestnfast.pl
 - Kaspersky       https://opentip.kaspersky.com/bestnfast.pl?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bestnfast.pl
 - Norton          https://safeweb.norton.com/report/show?url=bestnfast.pl
 - OpenDNS         https://domain.opendns.com/bestnfast.pl
 - URLVoid         https://www.urlvoid.com/scan/bestnfast.pl/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bestnfast.pl

```
