### ISSUE TITLE
bimbelyec.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#536]
https://www.google.com/search?q=https%3A%2F%2Fbimbelyec.com&num=50&safe=off&pws=0

https://rethinkdns.com/search?q=bimbelyec.com
https://www.virustotal.com/gui/url/ad25a84e2e9e728f2122050bb95e2eabca31dbb8e1d27d72092162b730cd4d3c?nocache=1

Is this still an active threat?

**Comment by hagezi** [comment]
```
Domain:
 - bimbelyec.com

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         YES
   ThreatView      YES
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         677446/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bimbelyec.com
 - VirusTotal      https://www.virustotal.com/en/domain/bimbelyec.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bimbelyec.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbimbelyec.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bimbelyec.com
 - Kaspersky       https://opentip.kaspersky.com/bimbelyec.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bimbelyec.com
 - Norton          https://safeweb.norton.com/report/show?url=bimbelyec.com
 - OpenDNS         https://domain.opendns.com/bimbelyec.com
 - URLVoid         https://www.urlvoid.com/scan/bimbelyec.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bimbelyec.com

```
