### ISSUE TITLE
budusushi.ua

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#537]
https://rethinkdns.com/search?q=budusushi.ua
https://www.virustotal.com/gui/url-analysis/u-bf9337e4d718b3be90ba7b293aa53f979cf3eaffc207f97034db5c782089fd7d-1677154068

**Comment by hagezi** [comment]
Phishing, report here: https://github.com/mitchellkrogza/Phishing.Database
```
Domain:
 - budusushi.ua

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         661323/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=budusushi.ua
 - VirusTotal      https://www.virustotal.com/en/domain/budusushi.ua/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/budusushi.ua
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbudusushi.ua
 - FortiGuard      https://www.fortiguard.com/webfilter?q=budusushi.ua
 - Kaspersky       https://opentip.kaspersky.com/budusushi.ua?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=budusushi.ua
 - Norton          https://safeweb.norton.com/report/show?url=budusushi.ua
 - OpenDNS         https://domain.opendns.com/budusushi.ua
 - URLVoid         https://www.urlvoid.com/scan/budusushi.ua/
 - Yandex          https://yandex.com/safety/?l10n=en&url=budusushi.ua

```
