### ISSUE TITLE
bullpro.net

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#538]
https://www.virustotal.com/gui/url/de0643cc8ea0556d33961a6a4968f60673887c2284e9c8c61fb892eed2d06086?nocache=1
https://rethinkdns.com/search?q=bullpro.net

**Comment by hagezi** [comment]
Blocked by VN Badsites Filter: https://gitlab.com/malware-filter/vn-badsite-filter

```
Domain:
 - budusushi.ua

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     YES

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         661323/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=budusushi.ua
 - VirusTotal      https://www.virustotal.com/en/domain/budusushi.ua/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/budusushi.ua
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbudusushi.ua
 - FortiGuard      https://www.fortiguard.com/webfilter?q=budusushi.ua
 - Kaspersky       https://opentip.kaspersky.com/budusushi.ua?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=budusushi.ua
 - Norton          https://safeweb.norton.com/report/show?url=budusushi.ua
 - OpenDNS         https://domain.opendns.com/budusushi.ua
 - URLVoid         https://www.urlvoid.com/scan/budusushi.ua/
 - Yandex          https://yandex.com/safety/?l10n=en&url=budusushi.ua

Sources:
 - mitchellkrogza_phishing.database_phishing-domains-active
pi@PiHoleVPN:~ $ check bullpro.net
Domain:
 - bullpro.net

Malware/Phishing/Scam:
 - Malicous?       POSSIBLE (1)

 - Threat?
   HaGeZi.TIF      YES
   ThreatFox       NO RESULT
   URLhaus         NO RESULT
   ThreatView      NO RESULT
   KADHosts        NO RESULT

 - Phishing?
   Phishing.Army   NO RESULT
   PT/OP/PH        NO RESULT
   Phishing.DB     NO RESULT

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         749638/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Yandex          OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - OVPN            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
 - Tiarap          OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=bullpro.net
 - VirusTotal      https://www.virustotal.com/en/domain/bullpro.net/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/bullpro.net
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbullpro.net
 - FortiGuard      https://www.fortiguard.com/webfilter?q=bullpro.net
 - Kaspersky       https://opentip.kaspersky.com/bullpro.net?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=bullpro.net
 - Norton          https://safeweb.norton.com/report/show?url=bullpro.net
 - OpenDNS         https://domain.opendns.com/bullpro.net
 - URLVoid         https://www.urlvoid.com/scan/bullpro.net/
 - Yandex          https://yandex.com/safety/?l10n=en&url=bullpro.net

```
