### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#543]
### Discussed in https://github.com/hagezi/dns-blocklists/discussions/542

<div type='discussions-op-text'>

<sup>Originally posted by **dmbmke** February 24, 2023</sup>
Ran into a false positive: onmilwaukee.com

It's just a local journalism site, nothing malicious AFAIK. 

Thanks for considering. </div>

**Comment by hagezi** [comment]
Thanks @dmbmke, checked, will be removed. ping @notracking

```
Domain:
 - onmilwaukee.com OK

Malware/Phishing/Scam:
 - Malicous?       UNLIKELY (1)

 - Threat?
   HaGeZi.TIF.LT   NO
   HaGeZi.TIF      NO
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       383552/-
 - Tranco:         41446/-
 - Chrome:         245851/-

Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=onmilwaukee.com
 - VirusTotal      https://www.virustotal.com/en/domain/onmilwaukee.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/onmilwaukee.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fonmilwaukee.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=onmilwaukee.com
 - Kaspersky       https://opentip.kaspersky.com/onmilwaukee.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=onmilwaukee.com
 - Norton          https://safeweb.norton.com/report/show?url=onmilwaukee.com
 - OpenDNS         https://domain.opendns.com/onmilwaukee.com
 - URLVoid         https://www.urlvoid.com/scan/onmilwaukee.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=onmilwaukee.com

Sources:
 - notracking_hosts-blocklists_adblock_adblock
 - notracking_hosts-blocklists_domains
 - stopforumspam.com_downloads_toxic_domains_whole

```
