### ISSUE TITLE
entertainzer.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#551]
#### Which domain(s) should be blocked?

entertainzer.com

#### Why should the domain(s) be blocked?

Warned as malicious by various threat intelligence.

**Comment by hagezi** [comment]
Requires further analysis, some of the reports are older and currently it has a clean appearance. It was once flagged as DGA Domain.

![grafik](https://user-images.githubusercontent.com/104343908/221357894-4d3ffe5a-675e-49f9-9f7e-1899e9fb33ea.png)

```
Domain:
 - entertainzer.com OK

Malware/Phishing/Scam:
 - Malicous?       NO RESULT - further analysis required

 - Threat?
   HaGeZi.TIF.LT   NO
   HaGeZi.TIF      NO
   HaGeZi.TIF.RAW  NO
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         261852/-
 - Chrome:         259036/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - DNSforge.de     OK
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=entertainzer.com
 - VirusTotal      https://www.virustotal.com/en/domain/entertainzer.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/entertainzer.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fentertainzer.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=entertainzer.com
 - Kaspersky       https://opentip.kaspersky.com/entertainzer.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=entertainzer.com
 - Norton          https://safeweb.norton.com/report/show?url=entertainzer.com
 - OpenDNS         https://domain.opendns.com/entertainzer.com
 - URLVoid         https://www.urlvoid.com/scan/entertainzer.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=entertainzer.com
```
