### ISSUE TITLE
Unblock this Site

### ISSUE THREAD

**Issue by SirKaushiK** [hagezi/dns-blocklists#557]
#### What adblocker/DNS cloud service are you using?
AdGuardHome Hosts

#### Which blocklists are used?
HaGeZi Multi Pro++
HaGeZi Ultimate
Threat Intelligence Feeds

#### Which domain(s) should be unblocked?
www.13tabs.com
13tabs.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Unblock the [www.13tabs.com](http://www.13tabs.com/) because this is a Search engine that made by individual developers. Here is article link. [DailyHunt News](https://m.dailyhunt.in/news/india/english/yourstory-epaper-dh3cb9c50f248d4dcdbaeaeab48287f080/startup+bharat+dhanbadbased+13tabs+is+working+to+make+the+internet+a+safer+place+for+people-newsid-n243297024)

**Comment by hagezi** [comment]
Thanks, will check.

ping source: @shadowwhisperer

**Comment by hagezi** [comment]
```
Domain:
 - 13tabs.com      OK

Malware/Phishing/Scam:
 - Malicous?       LIKELY (2)

 - Threat?
   HaGeZi.TIF.LT   NO
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  YES
   Quad9           NO
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       -/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL OK
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=13tabs.com
 - VirusTotal      https://www.virustotal.com/en/domain/13tabs.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/13tabs.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2F13tabs.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=13tabs.com
 - Kaspersky       https://opentip.kaspersky.com/13tabs.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=13tabs.com
 - Norton          https://safeweb.norton.com/report/show?url=13tabs.com
 - OpenDNS         https://domain.opendns.com/13tabs.com
 - URLVoid         https://www.urlvoid.com/scan/13tabs.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=13tabs.com
```
