### ISSUE TITLE
dvsdvsdvsdva.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#615]
#### What adblocker/DNS cloud service are you using?

`NextDNS`

#### Which blocklists are used?

`HaGeZi - Multi PRO`

#### Which domain(s) should be unblocked?

```
dvsdvsdvsdva.com
moon-100ge-streaming-server.dvsdvsdvsdva.com
moon-200ge-streaming-server.dvsdvsdvsdva.com
www.dvsdvsdvsdva.com
```

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

`filemoon.sx` use this domain for stream 

![20230305-1678033038](https://user-images.githubusercontent.com/9846948/222972757-a7cbdbf4-6c9d-466c-9267-210798921aaa.png)

Against DMCA I will not share direct sample link here.

**Comment by hagezi** [comment]
Flagged, blocked by Quad9

```
Domain:
 - moon-200ge-streaming-server.dvsdvsdvsdva.com OK

Malware/Phishing/Scam:
 - Malicous?       YES

 - Threat?
   HaGeZi.TIF.LT   NO
   HaGeZi.TIF      YES
   HaGeZi.TIF.RAW  NO
   Quad9           YES
   OpenDNS         NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   KADHosts        NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO
   CERT.PL         NO
   Phishing.DB     NO

Top 1M rank:
 - Umbrella:       180937/-
 - Tranco:         -/-
 - Chrome:         -/-

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     BLOCKED
 - OpenDNS         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        OK

Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        OK
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=moon-200ge-streaming-server.dvsdvsdvsdva.com
 - VirusTotal      https://www.virustotal.com/en/domain/moon-200ge-streaming-server.dvsdvsdvsdva.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/moon-200ge-streaming-server.dvsdvsdvsdva.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fmoon-200ge-streaming-server.dvsdvsdvsdva.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=moon-200ge-streaming-server.dvsdvsdvsdva.com&type=&engine=1
 - Kaspersky       https://opentip.kaspersky.com/moon-200ge-streaming-server.dvsdvsdvsdva.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=moon-200ge-streaming-server.dvsdvsdvsdva.com
 - Norton          https://safeweb.norton.com/report/show?url=moon-200ge-streaming-server.dvsdvsdvsdva.com
 - OpenDNS         https://domain.opendns.com/moon-200ge-streaming-server.dvsdvsdvsdva.com
 - URLVoid         https://www.urlvoid.com/scan/moon-200ge-streaming-server.dvsdvsdvsdva.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=moon-200ge-streaming-server.dvsdvsdvsdva.com
```
